/*
 * Proximity API
 * Proximity API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.proximax.proximity.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DashboardDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-05-13T22:46:23.640+02:00[Europe/Prague]")
public class DashboardDTO {
  public static final String SERIALIZED_NAME_HELLO = "hello";
  @SerializedName(SERIALIZED_NAME_HELLO)
  private String hello;


  public DashboardDTO hello(String hello) {
    
    this.hello = hello;
    return this;
  }

   /**
   * hello world implementation
   * @return hello
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "hello world implementation")

  public String getHello() {
    return hello;
  }


  public void setHello(String hello) {
    this.hello = hello;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardDTO dashboardDTO = (DashboardDTO) o;
    return Objects.equals(this.hello, dashboardDTO.hello);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hello);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardDTO {\n");
    sb.append("    hello: ").append(toIndentedString(hello)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

